### ISSUE TITLE
Holoviews import error when trying to import captest

### ISSUE THREAD

**Issue by matsuobasho** [pvcaptest/pvcaptest#103]
I installed the package using pip:
`pip install captest[optional]`

Actually I'm using pipenv as my environment manager but this likely doesn't matter.

When I run
`import captest as ct`

I get an error:
```
`AttributeError                            Traceback (most recent call last)
Cell In[6], line 2
      1 # import captest as ct
----> 2 from captest import capdata as pvc
      3 import pandas as pd
      4 import numpy as np

File c:\Users\Bob\.virtualenvs\env-name\Lib\site-packages\captest\__init__.py:1
----> 1 from captest import (
      2     capdata,
      3     util,
      4     prtest,
      5     columngroups,
      6     io,
      7 )
      9 from captest.io import (
     10     load_data,
     11     load_pvsyst,
     12     DataLoader,
     13 )
     15 from ._version import get_versions

File c:\Users\Bob\.virtualenvs\env-name\Lib\site-packages\captest\capdata.py:53
     51     from holoviews.plotting.links import DataLink
...
--> 603     resource = resource.replace('https://unpkg.com', config.npm_cdn)
    604     if resource.startswith(cdn_base):
    605         resource = resource.replace(cdn_base, CDN_DIST)

AttributeError: 'URL' object has no attribute 'replace'
```

Captest 0.12.1
Holoviews 1.18.3
Python 3.11.8
Bokeh 3.2.0

I also tried installing `pip install captest` (without optional) but getting the same error.

**Comment by bt-** [comment]
@matsuobasho, can you provide the full error? What operating system are you using? I just tried a fresh install using pip with the optional into a new conda env and wasn't able to re-create the error yet. My python, holoviews, and captest versions are the same as what you've listed. Bokeh though installed as v3.4.0 rather than v3.2.0.  When I downgraded to Bokeh v3.2.0 I did get an error when importing. 

Will you try installing a different version of Bokeh and see if that resolves the issue?

**Comment by matsuobasho** [comment]
@bt - thanks for the quick response.  Running on Windows 10.

I upgraded to Bokeh v3.4.0 as per your suggestion and it worked.
