### ISSUE TITLE
Need to be able to update translation after automatic mapping fails

### ISSUE THREAD

**Issue by jforbess** [pvcaptest/pvcaptest#35]
Once the automatic translation has failed, need a way to fix mistaken translations. 

Related to #27 making the __set_trans() method public.

**Comment by bt-** [comment]
@jforbess, this may not be the easiest solution, but you can manually edit the translation dictionary attribute (`CapData.trans`) to change the list of column names assigned to each category key or to add new category keys.  The `__set_trans()` method also sets the `CapData.trans_keys` attribute and calls `CapData.set_plot_attributes`, so you may might run into issues related to those attributes not matching your adjustments to `CapData.trans`.  Running `CapData__set_trans()` after your manual adjustments to `CapData.trans` may fix those issues.

The other option, which should be more reliable, is to make adjustments to the category dictionaries used to generate the `CapData.trans` keys and assign columns to them.  These are `capdata.type_defs`, `capdata.sub_type_defs`, and `capdata.irr_sensor_defs`.  These are ordered dictionaries and can be modified so you get a more useful translation dictionary.  If you have repeated search strings in the lists across different categories, you will get unexpected results.  

For example, the first two categories in the default `sub_type_defs` are
```
sub_type_defs = collections.OrderedDict([
                 ('ghi', [['sun2', 'global horizontal', 'ghi', 'global',
                           'GlobHor']]),
                 ('poa', [['sun', 'plane of array', 'poa', 'GlobInc']]),
```
If you add `'poa_global'` to the list paired with `'poa'`, the column with that string in it will still be assigned to the `'ghi'` category because `__series_type()` will attempt to assign the `'ghi'` category first and it will find 'global' within 'poa_global'.

#18 and #20 are also related to this issue.  The idea in #18 is to add some helper functions that could be passed to the pandas dataframe rename method.  I am thinking that would help with this issue quite a bit.
